package com.zz.common.dao;
import com.zz.common.model.Dtu;

public interface BdtuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ndtu
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ndtu
     *
     * @mbggenerated
     */
    int insert(Dtu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ndtu
     *
     * @mbggenerated
     */
    int insertSelective(Dtu record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ndtu
     *
     * @mbggenerated
     */
    Dtu selectByPrimaryKey(Integer id);
    Dtu selectMaxId(Integer id);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ndtu
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Dtu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ndtu
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Dtu record);
}