package com.zz.common.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.zz.common.model.TAmmeterInfo;

public interface TAmmeterInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ammeter_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String rowId);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ammeter_info
     *
     * @mbggenerated
     */
    int insertSelective(TAmmeterInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ammeter_info
     *
     * @mbggenerated
     */
    TAmmeterInfo selectByPrimaryKey(String rowId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ammeter_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TAmmeterInfo record);

    
    List<TAmmeterInfo> selectEpuNameByAm(@Param("epuDistrict") String epuDistrict);
    
    List<TAmmeterInfo> selectEpuInfoByRowId(@Param("rowId") String rowId,@Param("epuId") String epuId);
}