package com.zz.common.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.zz.common.model.TEpuInfo;

public interface TEpuInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_epu_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(TEpuInfo record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_epu_info
     *
     * @mbggenerated
     */
    int insertSelective(TEpuInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_epu_info
     *
     * @mbggenerated
     */
    TEpuInfo selectByPrimaryKey(String rowId);
    List<TEpuInfo> selectByEpuType( @Param("epuType")String epuType,@Param("epuDistrict")String epuDistrict);
    List<TEpuInfo> selectDistrictId(String rowId);
    List<TEpuInfo> selectAddressIdByDistrictId( String rowId);
    List<TEpuInfo> selectDIstinctByChannelId( @Param("districtId")String districtId,@Param("addressId")String addressId);
    List<TEpuInfo> selectEpuInfoByRowId(@Param("rowId") String rowId);
    List<TEpuInfo> selectEpuInfoByMark(TEpuInfo e);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_epu_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TEpuInfo record);
    
    int delMarkByRowId(@Param("rowId") String rowId);
    
    List<TEpuInfo>  checkEpName(@Param("epuName") String epuName,@Param("epuDistrict") String epuDistrict,@Param("epuType")String epuType);
    
    List<TEpuInfo> selectEpuInfos(TEpuInfo epuInfo);
}