package com.zz.common.model;

import java.io.Serializable;

public class Dtu implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ndtu.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ndtu.C_DistrictBCDId
     *
     * @mbggenerated
     */
    private String cDistrictbcdid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ndtu.C_AddressId
     *
     * @mbggenerated
     */
    private String cAddressid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ndtu.C_ChannelNum
     *
     * @mbggenerated
     */
    private Integer cChannelnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ndtu.C_HardwareVer
     *
     * @mbggenerated
     */
    private String cHardwarever;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ndtu.C_SoftwareVer
     *
     * @mbggenerated
     */
    private String cSoftwarever;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ndtu.C_FixIP
     *
     * @mbggenerated
     */
    private String cFixip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ndtu.C_LastComTime
     *
     * @mbggenerated
     */
    private String cLastcomtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ndtu.C_SoftUpdateDate
     *
     * @mbggenerated
     */
    private String cSoftupdatedate;

    public String getcInstalldateBegin() {
		return cInstalldateBegin;
	}

	public void setcInstalldateBegin(String cInstalldateBegin) {
		this.cInstalldateBegin = cInstalldateBegin;
	}

	public String getcInstalldateEnd() {
		return cInstalldateEnd;
	}

	public void setcInstalldateEnd(String cInstalldateEnd) {
		this.cInstalldateEnd = cInstalldateEnd;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ndtu.C_InstallDate
     *
     * @mbggenerated
     */
    private String cInstalldate;
    private String cInstalldateBegin;
    private String cInstalldateEnd;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ndtu.C_Desp
     *
     * @mbggenerated
     */
    private String cDesp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ndtu.nbDeviceId
     *
     * @mbggenerated
     */
    private String nbdeviceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_ndtu
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ndtu.id
     *
     * @return the value of t_ndtu.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ndtu.id
     *
     * @param id the value for t_ndtu.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ndtu.C_DistrictBCDId
     *
     * @return the value of t_ndtu.C_DistrictBCDId
     *
     * @mbggenerated
     */
    public String getcDistrictbcdid() {
        return cDistrictbcdid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ndtu.C_DistrictBCDId
     *
     * @param cDistrictbcdid the value for t_ndtu.C_DistrictBCDId
     *
     * @mbggenerated
     */
    public void setcDistrictbcdid(String cDistrictbcdid) {
        this.cDistrictbcdid = cDistrictbcdid == null ? null : cDistrictbcdid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ndtu.C_AddressId
     *
     * @return the value of t_ndtu.C_AddressId
     *
     * @mbggenerated
     */
    public String getcAddressid() {
        return cAddressid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ndtu.C_AddressId
     *
     * @param cAddressid the value for t_ndtu.C_AddressId
     *
     * @mbggenerated
     */
    public void setcAddressid(String cAddressid) {
        this.cAddressid = cAddressid == null ? null : cAddressid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ndtu.C_ChannelNum
     *
     * @return the value of t_ndtu.C_ChannelNum
     *
     * @mbggenerated
     */
    public Integer getcChannelnum() {
        return cChannelnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ndtu.C_ChannelNum
     *
     * @param cChannelnum the value for t_ndtu.C_ChannelNum
     *
     * @mbggenerated
     */
    public void setcChannelnum(Integer cChannelnum) {
        this.cChannelnum = cChannelnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ndtu.C_HardwareVer
     *
     * @return the value of t_ndtu.C_HardwareVer
     *
     * @mbggenerated
     */
    public String getcHardwarever() {
        return cHardwarever;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ndtu.C_HardwareVer
     *
     * @param cHardwarever the value for t_ndtu.C_HardwareVer
     *
     * @mbggenerated
     */
    public void setcHardwarever(String cHardwarever) {
        this.cHardwarever = cHardwarever == null ? null : cHardwarever.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ndtu.C_SoftwareVer
     *
     * @return the value of t_ndtu.C_SoftwareVer
     *
     * @mbggenerated
     */
    public String getcSoftwarever() {
        return cSoftwarever;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ndtu.C_SoftwareVer
     *
     * @param cSoftwarever the value for t_ndtu.C_SoftwareVer
     *
     * @mbggenerated
     */
    public void setcSoftwarever(String cSoftwarever) {
        this.cSoftwarever = cSoftwarever == null ? null : cSoftwarever.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ndtu.C_FixIP
     *
     * @return the value of t_ndtu.C_FixIP
     *
     * @mbggenerated
     */
    public String getcFixip() {
        return cFixip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ndtu.C_FixIP
     *
     * @param cFixip the value for t_ndtu.C_FixIP
     *
     * @mbggenerated
     */
    public void setcFixip(String cFixip) {
        this.cFixip = cFixip == null ? null : cFixip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ndtu.C_LastComTime
     *
     * @return the value of t_ndtu.C_LastComTime
     *
     * @mbggenerated
     */
    public String getcLastcomtime() {
        return cLastcomtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ndtu.C_LastComTime
     *
     * @param cLastcomtime the value for t_ndtu.C_LastComTime
     *
     * @mbggenerated
     */
    public void setcLastcomtime(String cLastcomtime) {
        this.cLastcomtime = cLastcomtime == null ? null : cLastcomtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ndtu.C_SoftUpdateDate
     *
     * @return the value of t_ndtu.C_SoftUpdateDate
     *
     * @mbggenerated
     */
    public String getcSoftupdatedate() {
        return cSoftupdatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ndtu.C_SoftUpdateDate
     *
     * @param cSoftupdatedate the value for t_ndtu.C_SoftUpdateDate
     *
     * @mbggenerated
     */
    public void setcSoftupdatedate(String cSoftupdatedate) {
        this.cSoftupdatedate = cSoftupdatedate == null ? null : cSoftupdatedate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ndtu.C_InstallDate
     *
     * @return the value of t_ndtu.C_InstallDate
     *
     * @mbggenerated
     */
    public String getcInstalldate() {
        return cInstalldate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ndtu.C_InstallDate
     *
     * @param cInstalldate the value for t_ndtu.C_InstallDate
     *
     * @mbggenerated
     */
    public void setcInstalldate(String cInstalldate) {
        this.cInstalldate = cInstalldate == null ? null : cInstalldate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ndtu.C_Desp
     *
     * @return the value of t_ndtu.C_Desp
     *
     * @mbggenerated
     */
    public String getcDesp() {
        return cDesp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ndtu.C_Desp
     *
     * @param cDesp the value for t_ndtu.C_Desp
     *
     * @mbggenerated
     */
    public void setcDesp(String cDesp) {
        this.cDesp = cDesp == null ? null : cDesp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ndtu.nbDeviceId
     *
     * @return the value of t_ndtu.nbDeviceId
     *
     * @mbggenerated
     */
    public String getNbdeviceid() {
        return nbdeviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ndtu.nbDeviceId
     *
     * @param nbdeviceid the value for t_ndtu.nbDeviceId
     *
     * @mbggenerated
     */
    public void setNbdeviceid(String nbdeviceid) {
        this.nbdeviceid = nbdeviceid == null ? null : nbdeviceid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ndtu
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Dtu other = (Dtu) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getcDistrictbcdid() == null ? other.getcDistrictbcdid() == null : this.getcDistrictbcdid().equals(other.getcDistrictbcdid()))
            && (this.getcAddressid() == null ? other.getcAddressid() == null : this.getcAddressid().equals(other.getcAddressid()))
            && (this.getcChannelnum() == null ? other.getcChannelnum() == null : this.getcChannelnum().equals(other.getcChannelnum()))
            && (this.getcHardwarever() == null ? other.getcHardwarever() == null : this.getcHardwarever().equals(other.getcHardwarever()))
            && (this.getcSoftwarever() == null ? other.getcSoftwarever() == null : this.getcSoftwarever().equals(other.getcSoftwarever()))
            && (this.getcFixip() == null ? other.getcFixip() == null : this.getcFixip().equals(other.getcFixip()))
            && (this.getcLastcomtime() == null ? other.getcLastcomtime() == null : this.getcLastcomtime().equals(other.getcLastcomtime()))
            && (this.getcSoftupdatedate() == null ? other.getcSoftupdatedate() == null : this.getcSoftupdatedate().equals(other.getcSoftupdatedate()))
            && (this.getcInstalldate() == null ? other.getcInstalldate() == null : this.getcInstalldate().equals(other.getcInstalldate()))
            && (this.getcDesp() == null ? other.getcDesp() == null : this.getcDesp().equals(other.getcDesp()))
            && (this.getNbdeviceid() == null ? other.getNbdeviceid() == null : this.getNbdeviceid().equals(other.getNbdeviceid()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ndtu
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getcDistrictbcdid() == null) ? 0 : getcDistrictbcdid().hashCode());
        result = prime * result + ((getcAddressid() == null) ? 0 : getcAddressid().hashCode());
        result = prime * result + ((getcChannelnum() == null) ? 0 : getcChannelnum().hashCode());
        result = prime * result + ((getcHardwarever() == null) ? 0 : getcHardwarever().hashCode());
        result = prime * result + ((getcSoftwarever() == null) ? 0 : getcSoftwarever().hashCode());
        result = prime * result + ((getcFixip() == null) ? 0 : getcFixip().hashCode());
        result = prime * result + ((getcLastcomtime() == null) ? 0 : getcLastcomtime().hashCode());
        result = prime * result + ((getcSoftupdatedate() == null) ? 0 : getcSoftupdatedate().hashCode());
        result = prime * result + ((getcInstalldate() == null) ? 0 : getcInstalldate().hashCode());
        result = prime * result + ((getcDesp() == null) ? 0 : getcDesp().hashCode());
        result = prime * result + ((getNbdeviceid() == null) ? 0 : getNbdeviceid().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ndtu
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", cDistrictbcdid=").append(cDistrictbcdid);
        sb.append(", cAddressid=").append(cAddressid);
        sb.append(", cChannelnum=").append(cChannelnum);
        sb.append(", cHardwarever=").append(cHardwarever);
        sb.append(", cSoftwarever=").append(cSoftwarever);
        sb.append(", cFixip=").append(cFixip);
        sb.append(", cLastcomtime=").append(cLastcomtime);
        sb.append(", cSoftupdatedate=").append(cSoftupdatedate);
        sb.append(", cInstalldate=").append(cInstalldate);
        sb.append(", cDesp=").append(cDesp);
        sb.append(", nbdeviceid=").append(nbdeviceid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}