package com.zz.common.model;

import java.io.Serializable;
import java.util.Date;

public class TAmmeterInfo implements Serializable {

public String getEpuName() {
	if(epuName==null)
	{
		epuName="";
	}
		return epuName;
	}

	public void setEpuName(String epuName) {
		this.epuName = epuName;
	}
	private String	epuId;
private String epuName;
private String epuProvinceName;
private String epuProvince;
private String epuCityName;
private String epuCity;
private String epuDistrictName;
private String epuDistrict;
private String epuType;
public String getEpuType() {
	if(epuType==null)
	{
		epuType="";
	}
	return epuType;
}

public void setEpuType(String epuType) {
	this.epuType = epuType;
}

public String getEpuProvinceName() {
	if(epuProvinceName==null)
	{
		epuProvinceName="";
	}
	return epuProvinceName;
}

public void setEpuProvinceName(String epuProvinceName) {
	this.epuProvinceName = epuProvinceName;
}

public String getEpuProvince() {
	if(epuProvince==null)
	{
		epuProvince="";
	}
	return epuProvince;
}

public String getEpuId() {
	if(epuId==null)
	{
		epuId="";
	}
	return epuId;
}

public void setEpuId(String epuId) {
	this.epuId = epuId;
}



public void setEpuProvince(String epuProvince) {
	this.epuProvince = epuProvince;
}

public String getEpuCityName() {
	if(epuCityName==null)
	{
		epuCityName="";
	}
	return epuCityName;
}

public void setEpuCityName(String epuCityName) {
	this.epuCityName = epuCityName;
}

public String getEpuCity() {
	if(epuCity==null)
	{
		epuCity="";
	}
	return epuCity;
}

public void setEpuCity(String epuCity) {
	this.epuCity = epuCity;
}

public String getEpuDistrictName() {
	if(epuDistrictName==null)
	{
		epuDistrictName="";
	}
	return epuDistrictName;
}

public void setEpuDistrictName(String epuDistrictName) {
	this.epuDistrictName = epuDistrictName;
}

public String getEpuDistrict() {
	if(epuDistrict==null)
	{
		epuDistrict="";
	}
	return epuDistrict;
}

public void setEpuDistrict(String epuDistrict) {
	this.epuDistrict = epuDistrict;
}

public static long getSerialversionuid() {
	return serialVersionUID;
}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ammeter_info.row_id
     *
     * @mbggenerated
     */
    private String rowId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ammeter_info.equ_id
     *
     * @mbggenerated
     */


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ammeter_info.ammeter_name
     *
     * @mbggenerated
     */
    private String ammeterName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ammeter_info.ammeter_id
     *
     * @mbggenerated
     */
    private String ammeterId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ammeter_info.house_id
     *
     * @mbggenerated
     */
    private String houseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ammeter_info.phase_remark
     *
     * @mbggenerated
     */
    private String phaseRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ammeter_info.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ammeter_info.CREATE_ID
     *
     * @mbggenerated
     */
    private String createId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ammeter_info.UPDATE_TIME
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ammeter_info.UPDATE_ID
     *
     * @mbggenerated
     */
    private String updateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ammeter_info.DEL_FLAG
     *
     * @mbggenerated
     */
    private String delFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ammeter_info.district_id
     *
     * @mbggenerated
     */
    private String districtId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ammeter_info.address_id
     *
     * @mbggenerated
     */
    private String addressId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ammeter_info.channel_id
     *
     * @mbggenerated
     */
    private String channelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_ammeter_info
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ammeter_info.row_id
     *
     * @return the value of t_ammeter_info.row_id
     *
     * @mbggenerated
     */
    public String getRowId() {
    	if(rowId==null)
    	{
    		rowId="";
    	}
        return rowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ammeter_info.row_id
     *
     * @param rowId the value for t_ammeter_info.row_id
     *
     * @mbggenerated
     */
    public void setRowId(String rowId) {
        this.rowId = rowId == null ? null : rowId.trim();
    }



    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ammeter_info.ammeter_name
     *
     * @return the value of t_ammeter_info.ammeter_name
     *
     * @mbggenerated
     */
    public String getAmmeterName() {
    	if(ammeterName==null)
    	{
    		ammeterName="";
    	}
        return ammeterName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ammeter_info.ammeter_name
     *
     * @param ammeterName the value for t_ammeter_info.ammeter_name
     *
     * @mbggenerated
     */
    public void setAmmeterName(String ammeterName) {
        this.ammeterName = ammeterName == null ? null : ammeterName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ammeter_info.ammeter_id
     *
     * @return the value of t_ammeter_info.ammeter_id
     *
     * @mbggenerated
     */
    public String getAmmeterId() {
    	if(ammeterId==null)
    	{
    		ammeterId="";
    	}
        return ammeterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ammeter_info.ammeter_id
     *
     * @param ammeterId the value for t_ammeter_info.ammeter_id
     *
     * @mbggenerated
     */
    public void setAmmeterId(String ammeterId) {
        this.ammeterId = ammeterId == null ? null : ammeterId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ammeter_info.house_id
     *
     * @return the value of t_ammeter_info.house_id
     *
     * @mbggenerated
     */
    public String getHouseId() {
    	if(houseId==null)
    	{
    		houseId="";
    	}
        return houseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ammeter_info.house_id
     *
     * @param houseId the value for t_ammeter_info.house_id
     *
     * @mbggenerated
     */
    public void setHouseId(String houseId) {
        this.houseId = houseId == null ? null : houseId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ammeter_info.phase_remark
     *
     * @return the value of t_ammeter_info.phase_remark
     *
     * @mbggenerated
     */
    public String getPhaseRemark() {
    	if(phaseRemark==null)
    	{
    		phaseRemark="";
    	}
        return phaseRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ammeter_info.phase_remark
     *
     * @param phaseRemark the value for t_ammeter_info.phase_remark
     *
     * @mbggenerated
     */
    public void setPhaseRemark(String phaseRemark) {
        this.phaseRemark = phaseRemark == null ? null : phaseRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ammeter_info.CREATE_TIME
     *
     * @return the value of t_ammeter_info.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ammeter_info.CREATE_TIME
     *
     * @param createTime the value for t_ammeter_info.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ammeter_info.CREATE_ID
     *
     * @return the value of t_ammeter_info.CREATE_ID
     *
     * @mbggenerated
     */
    public String getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ammeter_info.CREATE_ID
     *
     * @param createId the value for t_ammeter_info.CREATE_ID
     *
     * @mbggenerated
     */
    public void setCreateId(String createId) {
        this.createId = createId == null ? null : createId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ammeter_info.UPDATE_TIME
     *
     * @return the value of t_ammeter_info.UPDATE_TIME
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ammeter_info.UPDATE_TIME
     *
     * @param updateTime the value for t_ammeter_info.UPDATE_TIME
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ammeter_info.UPDATE_ID
     *
     * @return the value of t_ammeter_info.UPDATE_ID
     *
     * @mbggenerated
     */
    public String getUpdateId() {
        return updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ammeter_info.UPDATE_ID
     *
     * @param updateId the value for t_ammeter_info.UPDATE_ID
     *
     * @mbggenerated
     */
    public void setUpdateId(String updateId) {
        this.updateId = updateId == null ? null : updateId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ammeter_info.DEL_FLAG
     *
     * @return the value of t_ammeter_info.DEL_FLAG
     *
     * @mbggenerated
     */
    public String getDelFlag() {
    	if(delFlag==null)
    	{
    		delFlag="";
    	}
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ammeter_info.DEL_FLAG
     *
     * @param delFlag the value for t_ammeter_info.DEL_FLAG
     *
     * @mbggenerated
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag == null ? null : delFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ammeter_info.district_id
     *
     * @return the value of t_ammeter_info.district_id
     *
     * @mbggenerated
     */
    public String getDistrictId() {
    	if(districtId==null)
    	{
    		districtId="";
    	}
        return districtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ammeter_info.district_id
     *
     * @param districtId the value for t_ammeter_info.district_id
     *
     * @mbggenerated
     */
    public void setDistrictId(String districtId) {
        this.districtId = districtId == null ? null : districtId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ammeter_info.address_id
     *
     * @return the value of t_ammeter_info.address_id
     *
     * @mbggenerated
     */
    public String getAddressId() {
    	if(addressId==null)
    	{
    		addressId="";
    	}
        return addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ammeter_info.address_id
     *
     * @param addressId the value for t_ammeter_info.address_id
     *
     * @mbggenerated
     */
    public void setAddressId(String addressId) {
        this.addressId = addressId == null ? null : addressId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ammeter_info.channel_id
     *
     * @return the value of t_ammeter_info.channel_id
     *
     * @mbggenerated
     */
    public String getChannelId() {
    	if(channelId==null)
    	{
    		channelId="";
    	}
        return channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ammeter_info.channel_id
     *
     * @param channelId the value for t_ammeter_info.channel_id
     *
     * @mbggenerated
     */
    public void setChannelId(String channelId) {
        this.channelId = channelId == null ? null : channelId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ammeter_info
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TAmmeterInfo other = (TAmmeterInfo) that;
        return (this.getRowId() == null ? other.getRowId() == null : this.getRowId().equals(other.getRowId()))
            && (this.getEpuId() == null ? other.getEpuId() == null : this.getEpuId().equals(other.getEpuId()))
            && (this.getAmmeterName() == null ? other.getAmmeterName() == null : this.getAmmeterName().equals(other.getAmmeterName()))
            && (this.getAmmeterId() == null ? other.getAmmeterId() == null : this.getAmmeterId().equals(other.getAmmeterId()))
            && (this.getHouseId() == null ? other.getHouseId() == null : this.getHouseId().equals(other.getHouseId()))
            && (this.getPhaseRemark() == null ? other.getPhaseRemark() == null : this.getPhaseRemark().equals(other.getPhaseRemark()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getCreateId() == null ? other.getCreateId() == null : this.getCreateId().equals(other.getCreateId()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getUpdateId() == null ? other.getUpdateId() == null : this.getUpdateId().equals(other.getUpdateId()))
            && (this.getDelFlag() == null ? other.getDelFlag() == null : this.getDelFlag().equals(other.getDelFlag()))
            && (this.getDistrictId() == null ? other.getDistrictId() == null : this.getDistrictId().equals(other.getDistrictId()))
            && (this.getAddressId() == null ? other.getAddressId() == null : this.getAddressId().equals(other.getAddressId()))
            && (this.getChannelId() == null ? other.getChannelId() == null : this.getChannelId().equals(other.getChannelId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ammeter_info
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getRowId() == null) ? 0 : getRowId().hashCode());
        result = prime * result + ((getEpuId() == null) ? 0 : getEpuId().hashCode());
        result = prime * result + ((getAmmeterName() == null) ? 0 : getAmmeterName().hashCode());
        result = prime * result + ((getAmmeterId() == null) ? 0 : getAmmeterId().hashCode());
        result = prime * result + ((getHouseId() == null) ? 0 : getHouseId().hashCode());
        result = prime * result + ((getPhaseRemark() == null) ? 0 : getPhaseRemark().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getCreateId() == null) ? 0 : getCreateId().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getUpdateId() == null) ? 0 : getUpdateId().hashCode());
        result = prime * result + ((getDelFlag() == null) ? 0 : getDelFlag().hashCode());
        result = prime * result + ((getDistrictId() == null) ? 0 : getDistrictId().hashCode());
        result = prime * result + ((getAddressId() == null) ? 0 : getAddressId().hashCode());
        result = prime * result + ((getChannelId() == null) ? 0 : getChannelId().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ammeter_info
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", rowId=").append(rowId);
        sb.append(", epuId=").append(epuId);
        sb.append(", ammeterName=").append(ammeterName);
        sb.append(", ammeterId=").append(ammeterId);
        sb.append(", houseId=").append(houseId);
        sb.append(", phaseRemark=").append(phaseRemark);
        sb.append(", createTime=").append(createTime);
        sb.append(", createId=").append(createId);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", updateId=").append(updateId);
        sb.append(", delFlag=").append(delFlag);
        sb.append(", districtId=").append(districtId);
        sb.append(", addressId=").append(addressId);
        sb.append(", channelId=").append(channelId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}