package com.zz.common.model;

import java.io.Serializable;
import java.util.Date;

public class TEpuInfo implements Serializable {
	  /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_epu_info
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;
	  public static long getSerialversionuid() {
		return serialVersionUID;
	}
	  /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_epu_info.address_id
     *
     * @mbggenerated
     */
    private String addressId;
	  private String channelId;
	  /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_epu_info.CREATE_ID
     *
     * @mbggenerated
     */
    private String createId;
	  /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_epu_info.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;
	 
	  /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_epu_info.DEL_FLAG
     *
     * @mbggenerated
     */
    private String delFlag;
	  /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_epu_info.district_id
     *
     * @mbggenerated
     */
    private String districtId;
	  /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_epu_info.epu_city
     *
     * @mbggenerated
     */
    private String epuCity;
	private String epuCityName;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_epu_info.epu_district
     *
     * @mbggenerated
     */
    private String epuDistrict;

	private String epuDistrictName;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_epu_info.epu_local
     *
     * @mbggenerated
     */
    private String epuLocal;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_epu_info.epu_name
     *
     * @mbggenerated
     */
    private String epuName;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_epu_info.epu_parent_id
     *
     * @mbggenerated
     */
    private String epuParentId;

	private String epuParentName;

	private String epuParentType;

	private String epuParentTypeName;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_epu_info.epu_province
     *
     * @mbggenerated
     */
    private String epuProvince;

	private String epuProvinceName;

	private String epuStatus;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_epu_info.epu_type
     *
     * @mbggenerated
     */
    private String epuType;

	private String epuTypeName;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_epu_info.epu_xscale
     *
     * @mbggenerated
     */
    private Double epuXscale;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_epu_info.epu_yscale
     *
     * @mbggenerated
     */
    private Double epuYscale;

	private String lineId;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_epu_info.row_id
     *
     * @mbggenerated
     */
    private String rowId;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_epu_info.UPDATE_ID
     *
     * @mbggenerated
     */
    private String updateId;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_epu_info.UPDATE_TIME
     *
     * @mbggenerated
     */
    private Date updateTime;

	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_epu_info
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TEpuInfo other = (TEpuInfo) that;
        return (this.getRowId() == null ? other.getRowId() == null : this.getRowId().equals(other.getRowId()))
            && (this.getDistrictId() == null ? other.getDistrictId() == null : this.getDistrictId().equals(other.getDistrictId()))
            && (this.getEpuName() == null ? other.getEpuName() == null : this.getEpuName().equals(other.getEpuName()))
            && (this.getEpuLocal() == null ? other.getEpuLocal() == null : this.getEpuLocal().equals(other.getEpuLocal()))
            && (this.getEpuProvince() == null ? other.getEpuProvince() == null : this.getEpuProvince().equals(other.getEpuProvince()))
            && (this.getEpuCity() == null ? other.getEpuCity() == null : this.getEpuCity().equals(other.getEpuCity()))
            && (this.getEpuDistrict() == null ? other.getEpuDistrict() == null : this.getEpuDistrict().equals(other.getEpuDistrict()))
            && (this.getEpuType() == null ? other.getEpuType() == null : this.getEpuType().equals(other.getEpuType()))
            && (this.getEpuXscale() == null ? other.getEpuXscale() == null : this.getEpuXscale().equals(other.getEpuXscale()))
            && (this.getEpuYscale() == null ? other.getEpuYscale() == null : this.getEpuYscale().equals(other.getEpuYscale()))
            && (this.getEpuParentId() == null ? other.getEpuParentId() == null : this.getEpuParentId().equals(other.getEpuParentId()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getCreateId() == null ? other.getCreateId() == null : this.getCreateId().equals(other.getCreateId()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getUpdateId() == null ? other.getUpdateId() == null : this.getUpdateId().equals(other.getUpdateId()))
            && (this.getDelFlag() == null ? other.getDelFlag() == null : this.getDelFlag().equals(other.getDelFlag()))
            && (this.getAddressId() == null ? other.getAddressId() == null : this.getAddressId().equals(other.getAddressId()));
    }

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_epu_info.address_id
     *
     * @return the value of t_epu_info.address_id
     *
     * @mbggenerated
     */
    public String getAddressId() {
    	if(addressId==null)
		{
    		addressId="";
		}
        return addressId;
    }
    public String getChannelId() {
		if(channelId==null)
		{
			channelId="";
		}
		return channelId;
	}

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_epu_info.CREATE_ID
     *
     * @return the value of t_epu_info.CREATE_ID
     *
     * @mbggenerated
     */
    public String getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_epu_info.CREATE_TIME
     *
     * @return the value of t_epu_info.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_epu_info.DEL_FLAG
     *
     * @return the value of t_epu_info.DEL_FLAG
     *
     * @mbggenerated
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_epu_info.district_id
     *
     * @return the value of t_epu_info.district_id
     *
     * @mbggenerated
     */
    public String getDistrictId() {
    	if(districtId==null)
		{
    		districtId="";
		}
        return districtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_epu_info.epu_city
     *
     * @return the value of t_epu_info.epu_city
     *
     * @mbggenerated
     */
    public String getEpuCity() {
        return epuCity;
    }

    public String getEpuCityName() {
		if(epuCityName==null)
		{
			epuCityName="";
		}
		return epuCityName;
	}

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_epu_info.epu_district
     *
     * @return the value of t_epu_info.epu_district
     *
     * @mbggenerated
     */
    public String getEpuDistrict() {
    	if(epuDistrict==null)
		{
    		epuDistrict="";
		}
        return epuDistrict;
    }

    public String getEpuDistrictName() {
		if(epuDistrictName==null)
		{
			epuDistrictName="";
		}
		return epuDistrictName;
	}

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_epu_info.epu_local
     *
     * @return the value of t_epu_info.epu_local
     *
     * @mbggenerated
     */
    public String getEpuLocal() {
    	if(epuLocal==null)
		{
    		epuLocal="";
		}
        return epuLocal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_epu_info.epu_name
     *
     * @return the value of t_epu_info.epu_name
     *
     * @mbggenerated
     */
    public String getEpuName() {
    	if(epuName==null)
		{
    		epuName="";
		}
        return epuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_epu_info.epu_parent_id
     *
     * @return the value of t_epu_info.epu_parent_id
     *
     * @mbggenerated
     */
    public String getEpuParentId() {
    	if(epuParentId==null)
		{
    		epuParentId="";
		}
        return epuParentId;
    }

    public String getEpuParentName() {
		if(epuParentName==null)
		{
			epuParentName="";
		}
		return epuParentName;
	}

    public String getEpuParentType() {
		if(epuParentType==null)
		{
			epuParentType="";
		}
		return epuParentType;
	}

    public String getEpuParentTypeName() {
		if(epuParentTypeName==null)
		{
			epuParentTypeName="";
		}
		return epuParentTypeName;
	}

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_epu_info.epu_province
     *
     * @return the value of t_epu_info.epu_province
     *
     * @mbggenerated
     */
    public String getEpuProvince() {
        return epuProvince;
    }

    public String getEpuProvinceName() {
		if(epuProvinceName==null)
		{
			epuProvinceName="";
		}
		return epuProvinceName;
	}

    public String getEpuStatus() {
		if(epuStatus==null)
		{
			epuStatus="";
		}
		return epuStatus;
	}

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_epu_info.epu_type
     *
     * @return the value of t_epu_info.epu_type
     *
     * @mbggenerated
     */
    public String getEpuType() {
    	if(epuType==null)
		{
    		epuType="";
		}
        return epuType;
    }

    public String getEpuTypeName() {
		if(epuTypeName==null)
		{
			epuTypeName="";
		}
		return epuTypeName;
	}

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_epu_info.epu_xscale
     *
     * @return the value of t_epu_info.epu_xscale
     *
     * @mbggenerated
     */
    public Double getEpuXscale() {
        return epuXscale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_epu_info.epu_yscale
     *
     * @return the value of t_epu_info.epu_yscale
     *
     * @mbggenerated
     */
    public Double getEpuYscale() {
        return epuYscale;
    }

    public String getLineId() {
		if(lineId==null)
		{
			lineId="";
		}
		return lineId;
	}

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_epu_info.row_id
     *
     * @return the value of t_epu_info.row_id
     *
     * @mbggenerated
     */
    public String getRowId() {
        return rowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_epu_info.UPDATE_ID
     *
     * @return the value of t_epu_info.UPDATE_ID
     *
     * @mbggenerated
     */
    public String getUpdateId() {
        return updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_epu_info.UPDATE_TIME
     *
     * @return the value of t_epu_info.UPDATE_TIME
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_epu_info
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getRowId() == null) ? 0 : getRowId().hashCode());
        result = prime * result + ((getDistrictId() == null) ? 0 : getDistrictId().hashCode());
        result = prime * result + ((getEpuName() == null) ? 0 : getEpuName().hashCode());
        result = prime * result + ((getEpuLocal() == null) ? 0 : getEpuLocal().hashCode());
        result = prime * result + ((getEpuProvince() == null) ? 0 : getEpuProvince().hashCode());
        result = prime * result + ((getEpuCity() == null) ? 0 : getEpuCity().hashCode());
        result = prime * result + ((getEpuDistrict() == null) ? 0 : getEpuDistrict().hashCode());
        result = prime * result + ((getEpuType() == null) ? 0 : getEpuType().hashCode());
        result = prime * result + ((getEpuXscale() == null) ? 0 : getEpuXscale().hashCode());
        result = prime * result + ((getEpuYscale() == null) ? 0 : getEpuYscale().hashCode());
        result = prime * result + ((getEpuParentId() == null) ? 0 : getEpuParentId().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getCreateId() == null) ? 0 : getCreateId().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getUpdateId() == null) ? 0 : getUpdateId().hashCode());
        result = prime * result + ((getDelFlag() == null) ? 0 : getDelFlag().hashCode());
        result = prime * result + ((getAddressId() == null) ? 0 : getAddressId().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_epu_info.address_id
     *
     * @param addressId the value for t_epu_info.address_id
     *
     * @mbggenerated
     */
    public void setAddressId(String addressId) {
        this.addressId = addressId == null ? null : addressId.trim();
    }

    public void setChannelId(String channelId) {
		this.channelId = channelId;
	}

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_epu_info.CREATE_ID
     *
     * @param createId the value for t_epu_info.CREATE_ID
     *
     * @mbggenerated
     */
    public void setCreateId(String createId) {
        this.createId = createId == null ? null : createId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_epu_info.CREATE_TIME
     *
     * @param createTime the value for t_epu_info.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_epu_info.DEL_FLAG
     *
     * @param delFlag the value for t_epu_info.DEL_FLAG
     *
     * @mbggenerated
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag == null ? null : delFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_epu_info.district_id
     *
     * @param districtId the value for t_epu_info.district_id
     *
     * @mbggenerated
     */
    public void setDistrictId(String districtId) {
        this.districtId = districtId == null ? null : districtId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_epu_info.epu_city
     *
     * @param epuCity the value for t_epu_info.epu_city
     *
     * @mbggenerated
     */
    public void setEpuCity(String epuCity) {
        this.epuCity = epuCity == null ? null : epuCity.trim();
    }

    public void setEpuCityName(String epuCityName) {
		this.epuCityName = epuCityName;
	}

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_epu_info.epu_district
     *
     * @param epuDistrict the value for t_epu_info.epu_district
     *
     * @mbggenerated
     */
    public void setEpuDistrict(String epuDistrict) {
        this.epuDistrict = epuDistrict == null ? null : epuDistrict.trim();
    }

    public void setEpuDistrictName(String epuDistrictName) {
		this.epuDistrictName = epuDistrictName;
	}

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_epu_info.epu_local
     *
     * @param epuLocal the value for t_epu_info.epu_local
     *
     * @mbggenerated
     */
    public void setEpuLocal(String epuLocal) {
        this.epuLocal = epuLocal == null ? null : epuLocal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_epu_info.epu_name
     *
     * @param epuName the value for t_epu_info.epu_name
     *
     * @mbggenerated
     */
    public void setEpuName(String epuName) {
        this.epuName = epuName == null ? null : epuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_epu_info.epu_parent_id
     *
     * @param epuParentId the value for t_epu_info.epu_parent_id
     *
     * @mbggenerated
     */
    public void setEpuParentId(String epuParentId) {
        this.epuParentId = epuParentId == null ? null : epuParentId.trim();
    }

    public void setEpuParentName(String epuParentName) {
		this.epuParentName = epuParentName;
	}

    public void setEpuParentType(String epuParentType) {
		this.epuParentType = epuParentType;
	}

    public void setEpuParentTypeName(String epuParentTypeName) {
		this.epuParentTypeName = epuParentTypeName;
	}

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_epu_info.epu_province
     *
     * @param epuProvince the value for t_epu_info.epu_province
     *
     * @mbggenerated
     */
    public void setEpuProvince(String epuProvince) {
        this.epuProvince = epuProvince == null ? null : epuProvince.trim();
    }

    public void setEpuProvinceName(String epuProvinceName) {
		this.epuProvinceName = epuProvinceName;
	}

    public void setEpuStatus(String epuStatus) {
		this.epuStatus = epuStatus;
	}

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_epu_info.epu_type
     *
     * @param epuType the value for t_epu_info.epu_type
     *
     * @mbggenerated
     */
    public void setEpuType(String epuType) {
        this.epuType = epuType == null ? null : epuType.trim();
    }

    public void setEpuTypeName(String epuTypeName) {
		this.epuTypeName = epuTypeName;
	}

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_epu_info.epu_xscale
     *
     * @param epuXscale the value for t_epu_info.epu_xscale
     *
     * @mbggenerated
     */
    public void setEpuXscale(Double epuXscale) {
        this.epuXscale = epuXscale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_epu_info.epu_yscale
     *
     * @param epuYscale the value for t_epu_info.epu_yscale
     *
     * @mbggenerated
     */
    public void setEpuYscale(Double epuYscale) {
        this.epuYscale = epuYscale;
    }

    public void setLineId(String lineId) {
		this.lineId = lineId;
	}

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_epu_info.row_id
     *
     * @param rowId the value for t_epu_info.row_id
     *
     * @mbggenerated
     */
    public void setRowId(String rowId) {
        this.rowId = rowId == null ? null : rowId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_epu_info.UPDATE_ID
     *
     * @param updateId the value for t_epu_info.UPDATE_ID
     *
     * @mbggenerated
     */
    public void setUpdateId(String updateId) {
        this.updateId = updateId == null ? null : updateId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_epu_info.UPDATE_TIME
     *
     * @param updateTime the value for t_epu_info.UPDATE_TIME
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_epu_info
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", rowId=").append(rowId);
        sb.append(", districtId=").append(districtId);
        sb.append(", epuName=").append(epuName);
        sb.append(", epuLocal=").append(epuLocal);
        sb.append(", epuProvince=").append(epuProvince);
        sb.append(", epuCity=").append(epuCity);
        sb.append(", epuDistrict=").append(epuDistrict);
        sb.append(", epuType=").append(epuType);
        sb.append(", epuXscale=").append(epuXscale);
        sb.append(", epuYscale=").append(epuYscale);
        sb.append(", epuParentId=").append(epuParentId);
        sb.append(", createTime=").append(createTime);
        sb.append(", createId=").append(createId);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", updateId=").append(updateId);
        sb.append(", delFlag=").append(delFlag);
        sb.append(", addressId=").append(addressId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}